# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_banks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_access', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='Name',
            field=models.CharField(max_length=70),
        ),
    ]
