# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Banks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Banks'),
        ),
    ]
