# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_history_banks'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Access'),
        ),
        migrations.AddField(
            model_name='history',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Type'),
        ),
    ]
