# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190816_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('contact', models.IntegerField(max_length=10)),
                ('description', models.TextField(default=0, max_length=300)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='Accesses',
        ),
        migrations.RenameModel(
            old_name='Access',
            new_name='Types',
        ),
        migrations.RenameField(
            model_name='accesses',
            old_name='transaction_type',
            new_name='transaction_access',
        ),
        migrations.RenameField(
            model_name='banks',
            old_name='bank',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Type',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Banks',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='types',
            old_name='transaction_access',
            new_name='transaction_type',
        ),
        migrations.AddField(
            model_name='historymerch',
            name='access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Accesses'),
        ),
        migrations.AddField(
            model_name='historymerch',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Banks'),
        ),
        migrations.AddField(
            model_name='historymerch',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Types'),
        ),
    ]
