# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190818_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Access',
        ),
        migrations.AddField(
            model_name='history',
            name='access',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Accesses'),
        ),
        migrations.AlterField(
            model_name='history',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Types'),
        ),
    ]
