# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-18 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190818_0659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BanksMerch',
        ),
        migrations.RemoveField(
            model_name='historymerch',
            name='access',
        ),
        migrations.RemoveField(
            model_name='historymerch',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='historymerch',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='HistoryMerch',
        ),
    ]
